{{ include "common.minHelmVersion" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.fullname" (tuple . "-role-binding") }}
  labels:
{{ include "common.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.fullname" (tuple . "-role") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.fullname" . }}
    namespace: {{ .Release.Namespace }}