
{{- if and .Values.installCRDs.enabled (index .Values "trivy-operator").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.fullname" . }}-crds-installer
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
{{ include "common.annotations" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.fullname" . }}-crds-installer
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
{{ include "common.annotations" . | indent 4 }}    
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get" ]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.fullname" . }}-crds-installer
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded, hook-failed
{{ include "common.annotations" . | indent 4 }}    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.fullname" . }}-crds-installer
subjects:
  - kind: ServiceAccount
    name: {{ include "common.fullname" . }}-crds-installer
    namespace: {{ .Release.Namespace }}
{{- end }}
