{{ include "common.minHelmVersion" . }}
{{- if .Values.otel.metrics.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" (tuple . "-metrics-env-config") }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
data:
{{- if .Values.otel.metrics.prometheus.url }}
  PROMETHEUS_URL: {{ quote .Values.otel.metrics.prometheus.url }}
{{- end }}
{{- if (index .Values "kube-state-metrics").enabled }}
  KUBE_STATE_METRICS_URL: "{{ .Release.Name }}-kube-state-metrics.{{ .Release.Namespace }}.svc.cluster.local:8080"
{{- else }}
  KUBE_STATE_METRICS_URL: {{ quote (index .Values.otel.metrics "kube-state-metrics").url }}
{{- end }}
  OPENCOST_URL: "{{ .Release.Name }}-opencost.{{ .Release.Namespace }}.svc.cluster.local:9003"
{{- end}}