{{- if .Values.otel.api_token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
type: Opaque
data:
  SOLARWINDS_API_TOKEN: {{ .Values.otel.api_token | b64enc }}
{{- end}}
