{{- if .Values.network_topology.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.fullname" (tuple . "-obi-role") }}
  labels:
{{ include "common.labels" . | indent 4 }}
    app.kubernetes.io/component: rbac
  annotations:
{{ include "common.annotations" . | indent 4 }}
rules:
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "services", "nodes" ]
    verbs: [ "list", "watch", "get" ]
{{- end }}