{{- if .Values.autoupdate.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-autoupdate
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  schedule: {{ quote .Values.autoupdate.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "common.fullname" (tuple . "-autoupdate") }}
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
          containers:
          - name: helm-upgrade
            image: "{{ .Values.otel.image.repository | default "alpine/k8s" }}:{{ .Values.otel.image.tag | default "1.27.2@sha256:bbdbcb2e799b50958beb278de4a309d60bd238c14bdaff50c4e5ae42e446f745" }}"
            imagePullPolicy: {{ .Values.otel.image.pullPolicy }}
            command: 
              - /bin/bash
              - /scripts/helm-upgrade.sh
            volumeMounts:
              - name: helm-upgrade-script
                mountPath: /scripts/helm-upgrade.sh
                subPath: helm-upgrade.sh
          restartPolicy: Never
          volumes:
            - name: helm-upgrade-script
              configMap:
                name: {{ include "common.fullname" (tuple . "-autoupdate-script") }}
{{- end }}