{{- if .Values.autoupdate.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: helm-autoupdate
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  schedule: {{ quote .Values.autoupdate.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "common.fullname" (tuple . "-autoupdate") }}
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml .Values.imagePullSecrets | nindent 12 }}
          {{- end }}
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
                    - arm64
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux
          containers:
          - name: helm-upgrade
            image: "{{ include "common.image" (tuple . .Values.autoupdate (tuple "image" "autoupdate")) }}"
            imagePullPolicy: {{ .Values.otel.image.pullPolicy }}
            command: 
              - /bin/bash
              - /scripts/helm-upgrade.sh
            volumeMounts:
              - name: helm-upgrade-script
                mountPath: /scripts/helm-upgrade.sh
                subPath: helm-upgrade.sh
          restartPolicy: Never
          volumes:
            - name: helm-upgrade-script
              configMap:
                name: {{ include "common.fullname" (tuple . "-autoupdate-script") }}
{{- end }}