name: Release Helm Operator

on:
  push:
    paths:
      - deploy/helm/Chart.yaml
    branches:
      - master
      - release/**
env:
  DOCKERHUB_IMAGE: solarwinds/solarwinds-otel-operator
jobs:
  deploy_operator:
    if: false # Disabled until we start building the Operator again
    runs-on: ubuntu-latest
    permissions:
      contents: write # to push chart release and create a release (helm/chart-releaser-action)
      id-token: write # needed for signing
      pull-requests: write # needed to create pull-request
    name: Deploy operator and bundle images to dockerhub
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0
      - name: Set env
        run: |
          export VERSION=$(yq eval '.version' deploy/helm/Chart.yaml)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Install operator-sdk
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/v1.39.0/operator-sdk_linux_amd64
          chmod +x operator-sdk_linux_amd64
          sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk
      - name: Build images
        run: |
          "./.github/operator.sh"
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_SOLARWINDS_ORG_LOGIN }}
          password: ${{ secrets.ENOPS5919_OPENTELEMETRYCOLLECTOR_DOCKER_HUB_CI_OAT }}
      - name: Publish images
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE }}:${{ env.VERSION }}
          docker push ${{ env.DOCKERHUB_IMAGE }}:${{ env.VERSION }}-bundle
